### ISSUE TITLE
Provide more details for the errors 

### ISSUE THREAD

**Issue by yaxia** [Azure/azure-ruby-asm-core#12]
For the [issue #27](https://github.com/Azure/azure-storage-ruby/issues/27) reported for azure-storage,When some requests failed with an invalid header value, the header name and value are returned. The information are not included in the HTTPError. It would be better the error details can be returned from the error.
I will submit a PR to fix.

**Comment by yaxia** [comment]
I've submitted PR at: https://github.com/Azure/azure-ruby-asm-core/pull/13 , when azure-core is released, this issue will be addressed without updating azure-storage.

**Comment by veronicagg** [comment]
@yaxia PR is now merged.

**Comment by yaxia** [comment]
Fixed with #13
