### ISSUE TITLE
Version 0.1.6 on rubygems with invalid SHA 256

### ISSUE THREAD

**Issue by lthomaz** [Azure/azure-ruby-asm-core#32]
In the recent version of bundler (1.14.x) was introduced a checksum validation and in the `azure-core` version 0.1.6 released in RubyGems the SHA 256 checksum should be `b04f7f994e3abc31003139a7ff8a682980c1d064a906a3290d5c369685bc478b` but when you fetch gem file it was different: `68ebac6994412a775584478961747a215d0844737a8b9a91405a0ac77fe6c514`.

![screen shot 2017-01-24 at 11 26 53 am](https://cloud.githubusercontent.com/assets/28522/22248943/139dd8ec-e228-11e6-84b4-c2640dc87320.png)
 
I can not install the gem with bundle install. 
Please release a new version on RubyGems.

**Comment by sarangan12** [comment]
Related issues: https://github.com/lostisland/faraday_middleware/issues/152, https://github.com/bundler/bundler/issues/5332, https://github.com/rubygems/rubygems.org/issues/1551

**Comment by sarangan12** [comment]
A new version 0.1.7 has been released and this resolves the issue. Closing it
