### ISSUE TITLE
installing 'azure-core` is failing looking for `git` on our production systems

### ISSUE THREAD

**Issue by rameshjanjyam** [Azure/azure-ruby-asm-core#47]
i think because of this line in `.gemspec` 
```
s.files       = `git ls-files`.split("\n").reject { |f|  f.start_with?("test/unit") }
```
gem installation is failing looking for `git` on our `centos 73` boxes. 

we don't see a need to have version control software on our production servers. can this dependency on `git` be removed?

**Comment by veronicagg** [comment]
@vishrutshah do you have thoughts on this? I know we added it so we could avoid including tests in the gem.

**Comment by rameshjanjyam** [comment]
if it is used only for filtering some files out, this is how we do in .gemspec of one of our internal gem s
``` 
Dir.glob('lib/base/**/*', File::FNM_DOTMATCH).reject {|f| f =~ (/\.(\.|png)?$/)}
```
this way we don't have dependencies on other tools to include/exclude files.

**Comment by vishrutshah** [comment]
Let me look into this one.

**Comment by vishrutshah** [comment]
@rameshjanjyam I was trying to reproduce the issue but not able to. 

I tried installing `azure-core` gem on `cent-os` version `6.9` that do not have git and it installs successfully. Please see the logs below:

```
[vissha@centos-git ~]$ lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.9 (Final)
Release:	6.9
Codename:	Final

[vissha@centos-git ~]$ git
-bash: git: command not found

[vissha@centos-git ~]$ gem list | grep azure

[vissha@centos-git ~]$ gem install azure-core
Fetching: azure-core-0.1.12.gem (100%)
Successfully installed azure-core-0.1.12
Parsing documentation for azure-core-0.1.12
Installing ri documentation for azure-core-0.1.12
Done installing documentation for azure-core after 0 seconds
1 gem installed

[vissha@centos-git ~]$ gem list | grep azure
azure-core (0.1.12)

```

Are you trying to build the gem itself or just install it? Let me know. Thanks!

**Comment by rameshjanjyam** [comment]
Thanks for looking into it @vishrutshah 

Here is the Vagrant file I am using for the centos73 box 

```
$script = <<SCRIPT
  echo I am provisioning...
  sudo yum install -y ruby ruby-devel gcc gcc-c++ libxml2-devel libxslt-devel
  sudo gem update --system
  gem install bundler

  #azure-core-0.1.10 requires rake to be available
  gem install rake
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"
  config.vm.provision "shell", inline: $script
end
```

after `vagrant ssh` into the box I created a `Gemfile` with the below content. the apps we use have restriction on `nokogiri 1.5.11`
```
source 'http://rubygems.org'
 gem 'nokogiri','1.5.11'
 gem 'azure-core'
```
now running `bundle install` throws this error 

```
Installing azure-core 0.1.10 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/vagrant/.gem/ruby/gems/azure-core-0.1.10/ext
/usr/bin/ruby mkrf_conf.rb
Installing nokogiri ~> 1.6.0 with Ruby version:2.0.0
Building native extensions.  This could take a while...

current directory: /home/vagrant/.gem/ruby/gems/azure-core-0.1.10/ext
/usr/bin/ruby -rubygems /usr/local/share/gems/gems/rake-12.1.0/exe/rake
RUBYARCHDIR=/home/vagrant/.gem/ruby/extensions/x86_64-linux/azure-core-0.1.10
RUBYLIBDIR=/home/vagrant/.gem/ruby/extensions/x86_64-linux/azure-core-0.1.10
(in /home/vagrant/.gem/ruby/gems/azure-core-0.1.10)
rake aborted!
Errno::ENOENT: No such file or directory - git
/home/vagrant/.gem/ruby/gems/azure-core-0.1.10/Rakefile:18:in `eval'
(eval):28:in `block in <top (required)>'
(eval):19:in `new'
(eval):19:in `<top (required)>'
/home/vagrant/.gem/ruby/gems/azure-core-0.1.10/Rakefile:18:in `eval'
/home/vagrant/.gem/ruby/gems/azure-core-0.1.10/Rakefile:18:in `<top (required)>'
/usr/local/share/gems/gems/rake-12.1.0/exe/rake:27:in `<main>'
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /home/vagrant/.gem/ruby/gems/azure-core-0.1.10 for inspection.
Results logged to /home/vagrant/.gem/ruby/extensions/x86_64-linux/azure-core-0.1.10/gem_make.out

An error occurred while installing azure-core (0.1.10), and Bundler cannot continue.
Make sure that `gem install azure-core -v '0.1.10'` succeeds before bundling.
```

in the error you can see that it says `Errno::ENOENT: No such file or directory - git` 

since it said that i have installed `git` (`sudo yum install -y git`) and ran `bundle install` again. this time azure core is successful (only after installing git) 
```
Fetching azure-core 0.1.10
Installing azure-core 0.1.10 with native extensions
Bundle complete! 2 Gemfile dependencies, 6 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by yaxia** [comment]
@rameshjanjyam From the log you provided, you were installing azure-core 0.1.10 which had a post script (native extension) to install the compatible `nokogiri` gem. This post script was trying to called the `rakefile` and eventually called to  [gem_spec = eval(File.read('./azure-core.gemspec'))](https://github.com/Azure/azure-ruby-asm-core/blob/560a4b9b59d452ed030e4c7c0b85d322a5f42f16/Rakefile#L18) that required `git`.

So the solution for you is to upgrade to azure-core 0.1.12 which compatible with 0.1.10.

**Comment by rameshjanjyam** [comment]
thank you @yaxia. we will get nokogiri upgraded to `~> 1.6.0` and it should solve our problem. 

for version `0.1.10` - any reason why `nokogiri` is being installed in post script rather than being specified as a run time dependency.

**Comment by yaxia** [comment]
@rameshjanjyam The reason was `nokogiri` has strict Ruby version constrains since version 1.6. The version of runtime dependencies are written into the gem's metadata at packaging time, i.e. the `nokogiri` version is the one that's compatible with the Ruby version on the machine generates the `azure-core` gem. It is very possible that it is not compatible with the customer's environment. So we tried to install `nokogiri` in the post script that runs on the destination environment. It ensures the right version is selected.

You might want to ask why it switched to runtime dependency in the latest version. That's because many projects are using TavisCI for continuous integration. TravisCI uses `bundle exec` to run the validations which reads the dependencies from runtime dependencies. Although we have other solutions, but it requires some actions by the customers. Considering the popularity of `bundler`, we just leave the version selection job to it.

**Comment by rameshjanjyam** [comment]
Thank you for explaining the details @yaxia
