### ISSUE TITLE
RetryPolicy could not retry for timeout exceptions

### ISSUE THREAD

**Issue by devchick** [Azure/azure-ruby-asm-core#58]
I got a timeout exceptions for tcp connection, but never retry even if RetryPolicy enabled.

I think `Azure::Storage::Core::Filter::RetryPolicyFilter` of `azure-storage` gem has retry feature for timeout error ([here](https://github.com/Azure/azure-storage-ruby/blob/v0.15.0/lib/azure/storage/core/filter/retry_filter.rb#L114)).
But `Azure::Core::Http::RetryPolicy` cannot rescue such as `Errno::ETIMEDOUT` and `Timeout::Error` because it rescues only `StandardError`.

**Comment by yaxia** [comment]
Closing it per the comment in PR #56.

>Thanks for your reviewing. I fixed them.
but.... I made a mistake.
I met Faraday::Timeout, Errno::ETIMEDOUT. I made blind assumptions that rescue without arguments could not catch these exceptions like Timeout::Error. But, they are children of StandardError even Timeout::Error. (maybe.. I still wandering in Ruby 1.8 world...)
So, there is another reason of failed to retry. ~~I will make another issue.~~ Could you please ignore or reject this issue and the pull request.
