### ISSUE TITLE
Creating SharedKey instance with default parameter will throw error

### ISSUE THREAD

**Issue by yaxia** [Azure/azure-ruby-asm-core#7]
signer = Azure::Core::Auth::SharedKey.new

This call will throw error because `Azure.storage_account_name` is not defined. Please check the source [here](https://github.com/Azure/azure-ruby-asm-core/blob/master/lib/azure/core/auth/shared_key.rb#L31).

**Comment by veronicagg** [comment]
@yaxia Do you think you could submit a PR for a fix? The code used to pull the default values from the .env file.

**Comment by yaxia** [comment]
I will submit PR to fix it.

**Comment by yaxia** [comment]
@veronicagg Could you please merge the PR to address this issue? Thanks.

**Comment by yaxia** [comment]
Fixed with  #13
